version: '3.8'

services:
  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: template-app
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    environment:
      - APP_APP_PORT=9000
      - APP_DB_HOST=mysql
      - APP_DB_PORT=3306
      - APP_DB_USERNAME=root
      - APP_DB_PASSWORD=password
      - APP_DB_NAME=template_db
      - APP_REDIS_HOST=redis
      - APP_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - template-network

  # MySQL服务
  mysql:
    image: mysql:8.0
    container_name: template-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=template_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - template-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: template-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - template-network
    command: redis-server --appendonly yes

# 定义网络
networks:
  template-network:
    driver: bridge

# 定义数据卷
volumes:
  mysql-data:
  redis-data:
  go-modules: 