# 生产环境配置
app:
  name: "template"
  port: 7500
  mode: "release"                # 生产模式
  defaultRootPass: "123456"  # 生产环境请务必修改此密码
  timezone: "Asia/Shanghai"
  api_prefix: "/api/v1"
  static_path: "/static"
  upload_path: "uploads"
  max_upload_size: 20
  allowed_file_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

# 前端模块配置
frontend:
  admin:
    enabled: true
    route_prefix: "/admin"
    title: "管理后台"
    description: "系统管理后台"
  web:
    enabled: true
    route_prefix: "/"
    title: "用户端"
    description: "用户前端应用"
  fallback:
    enabled: true
    message: "服务正在维护中，请稍后访问"

# 数据库配置 - 生产环境
database:
  driver: "mysql"
  host: "localhost"              # 生产环境数据库地址
  port: 3306
  username: "template"           # 生产环境数据库用户
  password: "scRyXxfPsWjtbPSr" # 生产环境数据库密码
  name: "template"         # 生产环境数据库名
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  slow_query_threshold: 200
  enable_logging: false          # 生产环境关闭SQL日志
  table_prefix: ""

# JWT配置 - 生产环境
jwt:
  secret_key: "CHANGE-TO-YOUR-PRODUCTION-SECRET-KEY"  # 生产环境必须使用强密钥
  expires_in: 24
  refresh_expires_in: 168
  issuer: "template-app"
  audience: "template-users"
  blacklist_enabled: true
  blacklist_cleanup_interval: 24

# Redis配置 - 生产环境
redis:
  host: "localhost"              # 生产环境Redis地址
  port: 6379
  password: ""     # 生产环境Redis密码
  db: 0
  pool_size: 20                  # 生产环境增加连接池
  min_idle_conns: 10
  max_conn_age: 3600
  idle_timeout: 240
  read_timeout: 3
  write_timeout: 3
  dial_timeout: 5

# 日志配置 - 生产环境
log:
  level: "info"                  # 生产环境日志级别
  path: "logs"
  filename: "app.log"
  max_size: 100
  max_backups: 30                # 生产环境保留更多日志
  max_age: 30                    # 生产环境保留30天日志
  compress: true
  json_format: true              # 生产环境使用JSON格式便于分析
  show_caller: false             # 生产环境关闭调用者信息
  show_line: false               # 生产环境关闭行号信息
  show_stack: false
  enable_console: false          # 生产环境关闭控制台输出

# 邮件服务配置 - 生产环境
mail:
  host: "smtpdm.aliyun.com"   # 生产环境SMTP服务器
  port: 465
  username: "nine_team@nineai.jiangly.com"
  password: "Nine98Mailer"      # 生产环境SMTP密码
  from: "nine_team@nineai.jiangly.com"
  from_name: "系统通知"
  reply_to: "nine_team@nineai.jiangly.com"
  ssl: true
  enabled: true                  # 生产环境启用邮件服务
  template_path: "templates/mail"
  max_retries: 3
  retry_interval: 5

# CORS配置 - 生产环境
cors:
  enabled: true
  allowed_origins:               # 生产环境只允许特定域名
    - "https://template.mmmss.com"
    - "http://template.mmmss.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
  max_age: 86400
  expose_headers:
    - "Content-Length"
    - "Content-Type" 